<#
.SYNOPSIS
    Exports permissions drift findings into a compliance evidence package.

.DESCRIPTION
    Formats the drift report and baseline snapshot into a regulatory examination
    evidence package. Produces CSV and summary JSON outputs with counts by drift
    type and risk tier, including before/after permission state for each changed item.

    Output is suitable for FFIEC, SEC, FINRA, and SOX examination response.
    All evidence artifacts include SHA-256 companion files for integrity verification.

.PARAMETER DriftReportPath
    Path to the drift report JSON file generated by Invoke-DriftScan.ps1.

.PARAMETER BaselinePath
    Path to the baseline snapshot JSON file.

.PARAMETER OutputPath
    Directory for evidence package output. Defaults to ./evidence.

.PARAMETER ConfigurationTier
    Configuration tier for evidence retention settings. Valid values: baseline, recommended, regulated.

.EXAMPLE
    .\Export-DriftEvidence.ps1 -DriftReportPath "./reports/drift-report-latest.json" -BaselinePath "./baselines/latest-baseline.json"

.EXAMPLE
    .\Export-DriftEvidence.ps1 -DriftReportPath "./reports/drift-report-20250101T120000.json" -OutputPath "./evidence" -ConfigurationTier regulated
#>
[CmdletBinding()]
param(
    [Parameter()]
    [string]$DriftReportPath,

    [Parameter()]
    [string]$BaselinePath,

    [Parameter()]
    [string]$OutputPath = './evidence',

    [Parameter()]
    [ValidateSet('baseline', 'recommended', 'regulated')]
    [string]$ConfigurationTier = 'baseline'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path
Import-Module (Join-Path $repoRoot 'scripts\common\GraphAuth.psm1') -Force
Import-Module (Join-Path $repoRoot 'scripts\common\EvidenceExport.psm1') -Force

#region Helper Functions

function Write-JsonWithHash {
    <#
    .SYNOPSIS
        Writes a JSON file and its SHA-256 companion hash file.
    #>
    param(
        [string]$FilePath,
        [object]$Data
    )

    $json = $Data | ConvertTo-Json -Depth 15
    Set-Content -Path $FilePath -Value $json -Encoding UTF8

    $hashInfo = Write-CopilotGovSha256File -Path $FilePath

    return [pscustomobject]@{
        FilePath = $FilePath
        Hash     = $hashInfo.Hash
        HashFile = $hashInfo.HashPath
    }
}

function ConvertTo-DriftCsv {
    <#
    .SYNOPSIS
        Converts drift items to a flat CSV-compatible format.
    #>
    param([array]$DriftItems)

    $csvRows = @()
    foreach ($item in $DriftItems) {
        $beforePrincipal = if ($item.Before) { $item.Before.principalName } else { '' }
        $beforeLevel = if ($item.Before) { $item.Before.permissionLevel } else { '' }
        $afterPrincipal = if ($item.After) { $item.After.principalName } else { '' }
        $afterLevel = if ($item.After) { $item.After.permissionLevel } else { '' }

        $csvRows += [pscustomobject]@{
            SiteUrl         = $item.SiteUrl
            ItemPath        = $item.ItemPath
            DriftType       = $item.DriftType
            RiskTier        = $item.RiskTier
            RiskScore       = $item.RiskScore
            BeforePrincipal = $beforePrincipal
            BeforeLevel     = $beforeLevel
            AfterPrincipal  = $afterPrincipal
            AfterLevel      = $afterLevel
            DetectedAt      = $item.DetectedAt
        }
    }
    return $csvRows
}

#endregion

#region Main Logic

# Ensure output directory exists
if (-not (Test-Path $OutputPath)) {
    New-Item -ItemType Directory -Path $OutputPath -Force | Out-Null
}

# Load drift report (or generate sample data)
$driftReport = $null
if ($DriftReportPath -and (Test-Path $DriftReportPath)) {
    $driftReport = Get-Content -Path $DriftReportPath -Raw | ConvertFrom-Json
}
else {
    Write-Warning "Drift report not found at '$DriftReportPath' — generating sample evidence package."
    $driftReport = [pscustomobject]@{
        generatedAt     = (Get-Date).ToString('o')
        tenantUrl       = 'https://contoso.sharepoint.com'
        baselinePath    = './baselines/latest-baseline.json'
        totalDriftItems = 4
        summary         = [pscustomobject]@{
            added   = 2
            removed = 1
            changed = 1
            high    = 1
            medium  = 2
            low     = 1
        }
        items = @(
            [pscustomobject]@{
                SiteUrl    = 'https://contoso.sharepoint.com/sites/Finance'
                ItemPath   = 'Shared Documents/Confidential'
                DriftType  = 'ADDED'
                Before     = $null
                After      = [pscustomobject]@{ principalName = 'External Consultant'; principalType = 'ExternalUser'; permissionLevel = 'Contribute' }
                RiskScore  = 75
                RiskTier   = 'HIGH'
                DetectedAt = (Get-Date).ToString('o')
            }
            [pscustomobject]@{
                SiteUrl    = 'https://contoso.sharepoint.com/sites/Trading-Desk'
                ItemPath   = 'Trading Records'
                DriftType  = 'CHANGED'
                Before     = [pscustomobject]@{ principalName = 'Trading Analysts'; principalType = 'SecurityGroup'; permissionLevel = 'Read' }
                After      = [pscustomobject]@{ principalName = 'Trading Analysts'; principalType = 'SecurityGroup'; permissionLevel = 'FullControl' }
                RiskScore  = 55
                RiskTier   = 'MEDIUM'
                DetectedAt = (Get-Date).ToString('o')
            }
            [pscustomobject]@{
                SiteUrl    = 'https://contoso.sharepoint.com/sites/Client-Advisory'
                ItemPath   = 'Client Reports/2025-Q1.xlsx'
                DriftType  = 'ADDED'
                Before     = $null
                After      = [pscustomobject]@{ principalName = 'All Employees'; principalType = 'OrganizationWide'; permissionLevel = 'Read' }
                RiskScore  = 45
                RiskTier   = 'MEDIUM'
                DetectedAt = (Get-Date).ToString('o')
            }
            [pscustomobject]@{
                SiteUrl    = 'https://contoso.sharepoint.com/sites/HR-Confidential'
                ItemPath   = 'Policies/Travel-Policy.docx'
                DriftType  = 'REMOVED'
                Before     = [pscustomobject]@{ principalName = 'HR Admins'; principalType = 'SharePointGroup'; permissionLevel = 'FullControl' }
                After      = $null
                RiskScore  = 10
                RiskTier   = 'LOW'
                DetectedAt = (Get-Date).ToString('o')
            }
        )
    }
}

$driftItems = $driftReport.items

# 1. Export drift findings JSON
$findingsData = [pscustomobject]@{
    solution          = '17-sharepoint-permissions-drift'
    solutionCode      = 'SPD'
    exportedAt        = (Get-Date).ToString('o')
    configurationTier = $ConfigurationTier
    totalFindings     = $driftItems.Count
    findings          = $driftItems
}
$findingsResult = Write-JsonWithHash -FilePath (Join-Path $OutputPath 'drift-findings.json') -Data $findingsData

# 2. Export drift findings CSV
$csvRows = ConvertTo-DriftCsv -DriftItems $driftItems
$csvPath = Join-Path $OutputPath 'drift-findings.csv'
$csvRows | Export-Csv -Path $csvPath -NoTypeInformation -Encoding UTF8
Write-Host "Drift findings CSV exported: $csvPath"

# 3. Export baseline snapshot (copy or reference)
$baselineSnapshotData = $null
if ($BaselinePath -and (Test-Path $BaselinePath)) {
    $baselineSnapshotData = Get-Content -Path $BaselinePath -Raw | ConvertFrom-Json
}
else {
    $baselineSnapshotData = [pscustomobject]@{
        note = 'Baseline snapshot not available — sample reference only'
        capturedAt = (Get-Date).AddDays(-7).ToString('o')
    }
}
$baselineResult = Write-JsonWithHash -FilePath (Join-Path $OutputPath 'baseline-snapshot.json') -Data $baselineSnapshotData

# 4. Export reversion log (if available)
$reversionLogPath = $null
if ($DriftReportPath) {
    $reportDir = Split-Path $DriftReportPath -Parent
    $existingLogs = Get-ChildItem -Path $reportDir -Filter 'reversion-log-*.json' -ErrorAction SilentlyContinue
    if ($existingLogs) {
        $latestLog = $existingLogs | Sort-Object Name -Descending | Select-Object -First 1
        $reversionData = Get-Content -Path $latestLog.FullName -Raw | ConvertFrom-Json
        $reversionResult = Write-JsonWithHash -FilePath (Join-Path $OutputPath 'reversion-log.json') -Data $reversionData
        $reversionLogPath = $reversionResult.FilePath
    }
}

if (-not $reversionLogPath) {
    $emptyReversion = [pscustomobject]@{
        note = 'No reversion actions recorded for this reporting period'
        entries = @()
    }
    $reversionResult = Write-JsonWithHash -FilePath (Join-Path $OutputPath 'reversion-log.json') -Data $emptyReversion
}

# 5. Build evidence summary
$evidenceSummary = [pscustomobject]@{
    metadata   = [pscustomobject]@{
        solution      = '17-sharepoint-permissions-drift'
        solutionCode  = 'SPD'
        exportVersion = 'v0.1.0'
        exportedAt    = (Get-Date).ToString('o')
        tier          = $ConfigurationTier
        periodStart   = (Get-Date).AddDays(-30).ToString('o')
        periodEnd     = (Get-Date).ToString('o')
    }
    summary    = [pscustomobject]@{
        overallStatus  = 'partial'
        recordCount    = $driftItems.Count
        findingCount   = $driftItems.Count
        exceptionCount = 0
        byDriftType    = [pscustomobject]@{
            added   = ($driftItems | Where-Object { $_.DriftType -eq 'ADDED' }).Count
            removed = ($driftItems | Where-Object { $_.DriftType -eq 'REMOVED' }).Count
            changed = ($driftItems | Where-Object { $_.DriftType -eq 'CHANGED' }).Count
        }
        byRiskTier     = [pscustomobject]@{
            high   = ($driftItems | Where-Object { $_.RiskTier -eq 'HIGH' }).Count
            medium = ($driftItems | Where-Object { $_.RiskTier -eq 'MEDIUM' }).Count
            low    = ($driftItems | Where-Object { $_.RiskTier -eq 'LOW' }).Count
        }
    }
    controls   = @(
        [pscustomobject]@{ controlId = '1.2'; status = 'partial'; notes = 'Documents drift detection pattern for site sharing settings' }
        [pscustomobject]@{ controlId = '1.4'; status = 'partial'; notes = 'Documents external user access drift detection' }
        [pscustomobject]@{ controlId = '1.6'; status = 'partial'; notes = 'Documents unique permission entry tracking' }
        [pscustomobject]@{ controlId = '2.5'; status = 'monitor-only'; notes = 'Documents reversion workflow pattern; approval-gate default' }
    )
    artifacts  = @(
        [pscustomobject]@{ name = 'drift-findings.json'; path = $findingsResult.FilePath; hash = $findingsResult.Hash }
        [pscustomobject]@{ name = 'drift-findings.csv'; path = $csvPath; hash = (Get-FileHash -Path $csvPath -Algorithm SHA256).Hash }
        [pscustomobject]@{ name = 'baseline-snapshot.json'; path = $baselineResult.FilePath; hash = $baselineResult.Hash }
        [pscustomobject]@{ name = 'reversion-log.json'; path = $reversionResult.FilePath; hash = $reversionResult.Hash }
    )
}

$summaryResult = Write-JsonWithHash -FilePath (Join-Path $OutputPath 'evidence-summary.json') -Data $evidenceSummary
Write-Host "Evidence summary exported: $($summaryResult.FilePath)"

#endregion

# Return summary
[pscustomobject]@{
    OutputPath     = $OutputPath
    ArtifactCount  = $evidenceSummary.artifacts.Count
    FindingCount   = $driftItems.Count
    Tier           = $ConfigurationTier
    SummaryFile    = $summaryResult.FilePath
    Status         = 'EvidenceExported'
}
