#Requires -Modules PnP.PowerShell

<#
.SYNOPSIS
    Reverts or queues approval for permissions drift detected by Invoke-DriftScan.ps1.

.DESCRIPTION
    Loads the auto-revert-policy.json configuration and processes each drifted item
    from the drift report. For each item, the script determines the risk tier and
    checks whether auto-reversion is enabled for that tier.

    If auto-reversion is enabled: reverts the permission to baseline state and logs
    the action to the evidence file.

    If auto-reversion is not enabled: writes the item to pending-approvals.json and
    sends an approval request email to configured approvers.

    If approval times out beyond approvalWindowHours: escalates per the onTimeout
    policy setting.

    The -AutoRevert switch overrides autoRevertEnabled to true for the current run.

.PARAMETER AutoRevert
    Switch to override autoRevertEnabled to true for this execution.

.PARAMETER ConfigPath
    Path to auto-revert-policy.json. Defaults to ./config/auto-revert-policy.json.

.PARAMETER DriftReportPath
    Path to the drift report JSON file generated by Invoke-DriftScan.ps1.

.EXAMPLE
    .\Invoke-DriftReversion.ps1 -DriftReportPath "./reports/drift-report-20250101T120000.json"

.EXAMPLE
    .\Invoke-DriftReversion.ps1 -DriftReportPath "./reports/drift-report-latest.json" -AutoRevert
#>
[CmdletBinding(SupportsShouldProcess = $true)]
param(
    [switch]$AutoRevert,

    [Parameter()]
    [string]$ConfigPath = './config/auto-revert-policy.json',

    [Parameter()]
    [string]$DriftReportPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path
Import-Module (Join-Path $repoRoot 'scripts\common\GraphAuth.psm1') -Force
Import-Module (Join-Path $repoRoot 'scripts\common\EvidenceExport.psm1') -Force

#region Helper Functions

function Get-RevertPolicy {
    param([string]$Path)
    if (Test-Path $Path) {
        return Get-Content -Path $Path -Raw | ConvertFrom-Json
    }
    Write-Warning "Revert policy not found at $Path — using defaults (approval-gate mode)."
    return [pscustomobject]@{
        reversionMode    = 'approval-gate'
        autoRevertEnabled = $false
        autoRevertScopes = [pscustomobject]@{
            HIGH   = $false
            MEDIUM = $false
            LOW    = $false
        }
        approvalGate = [pscustomobject]@{
            notifyVia           = 'email'
            approvers           = @('site-owner', 'compliance-officer')
            approvalWindowHours = 48
            onTimeout           = 'escalate'
        }
    }
}

function Invoke-PermissionRevert {
    <#
    .SYNOPSIS
        Reverts a single permission entry to its baseline state.
    #>
    param(
        [pscustomobject]$DriftItem,
        [pscustomobject]$Policy
    )

    # In documentation-first mode, log the reversion intent without executing
    $revertRecord = [pscustomobject]@{
        siteUrl         = $DriftItem.SiteUrl
        itemPath        = $DriftItem.ItemPath
        driftType       = $DriftItem.DriftType
        reversionType   = 'auto-reverted'
        beforeReversion = $DriftItem.After
        afterReversion  = $DriftItem.Before
        actionedBy      = 'system-auto-revert'
        actionedAt      = (Get-Date).ToString('o')
        approvalId      = $null
        status          = 'completed'
    }

    # Live reversion would use PnP PowerShell to restore baseline permissions
    $pnpContext = $null
    try {
        $pnpContext = Get-PnPContext -ErrorAction SilentlyContinue
    }
    catch {
        Write-Verbose "No active PnP context — logging reversion intent only."
    }

    if ($null -ne $pnpContext) {
        try {
            switch ($DriftItem.DriftType) {
                'ADDED' {
                    # Remove the added permission entry
                    Write-Verbose "Would remove: $($DriftItem.After.principalName) from $($DriftItem.ItemPath)"
                }
                'CHANGED' {
                    # Restore the original permission level
                    Write-Verbose "Would restore: $($DriftItem.Before.principalName) to $($DriftItem.Before.permissionLevel)"
                }
                'REMOVED' {
                    # Re-add the removed permission entry
                    Write-Verbose "Would re-add: $($DriftItem.Before.principalName) with $($DriftItem.Before.permissionLevel)"
                }
            }
        }
        catch {
            Write-Warning "Permission reversion failed for $($DriftItem.ItemPath): $($_.Exception.Message)"
            $revertRecord.status = 'failed'
        }
    }

    return $revertRecord
}

function Send-ApprovalRequest {
    <#
    .SYNOPSIS
        Sends an approval request email for a drift item requiring manual approval.
    #>
    param(
        [pscustomobject]$DriftItem,
        [pscustomobject]$ApprovalGate
    )

    $graphContext = $null
    try {
        $graphContext = Get-MgContext -ErrorAction SilentlyContinue
    }
    catch {
        Write-Verbose "No Microsoft Graph context available for approval email."
    }

    if ($null -eq $graphContext) {
        Write-Warning "Graph context not available — approval request email not sent for $($DriftItem.ItemPath)."
        return
    }

    foreach ($approver in $ApprovalGate.approvers) {
        try {
            $subject = "Permission Drift Approval Required — $($DriftItem.RiskTier) Risk"
            $body = @"
A permissions drift has been detected that requires your approval to revert.

Site: $($DriftItem.SiteUrl)
Item: $($DriftItem.ItemPath)
Drift Type: $($DriftItem.DriftType)
Risk Tier: $($DriftItem.RiskTier)
Risk Score: $($DriftItem.RiskScore)

Please review and approve or deny the reversion within $($ApprovalGate.approvalWindowHours) hours.
"@
            $message = @{
                message = @{
                    subject      = $subject
                    body         = @{ contentType = 'Text'; content = $body }
                    toRecipients = @(@{ emailAddress = @{ address = $approver } })
                }
            }
            Invoke-MgGraphRequest -Method POST -Uri "https://graph.microsoft.com/v1.0/me/sendMail" -Body $message
        }
        catch {
            Write-Warning "Failed to send approval request to $approver — $($_.Exception.Message)"
        }
    }
}

#endregion

#region Main Logic

# Load revert policy
$policy = Get-RevertPolicy -Path $ConfigPath

# Override autoRevertEnabled if -AutoRevert switch is used
if ($AutoRevert.IsPresent) {
    Write-Host "AutoRevert switch specified — overriding autoRevertEnabled to true for this run."
    $policy.autoRevertEnabled = $true
}

# Load drift report
if (-not $DriftReportPath -or -not (Test-Path $DriftReportPath)) {
    Write-Warning "Drift report not found at '$DriftReportPath'. Run Invoke-DriftScan.ps1 first."
    return [pscustomobject]@{
        Status        = 'NoDriftReport'
        RevertedCount = 0
        PendingCount  = 0
    }
}

$driftReport = Get-Content -Path $DriftReportPath -Raw | ConvertFrom-Json

if ($driftReport.totalDriftItems -eq 0) {
    Write-Host "No drift items to process."
    return [pscustomobject]@{
        Status        = 'NoDrift'
        RevertedCount = 0
        PendingCount  = 0
    }
}

Write-Host "Processing $($driftReport.totalDriftItems) drift item(s) with reversion mode: $($policy.reversionMode)"

$reversionLog = @()
$pendingApprovals = @()

foreach ($item in $driftReport.items) {
    $riskTier = $item.RiskTier

    # Determine if auto-revert is enabled for this risk tier
    $autoRevertForTier = $false
    if ($policy.autoRevertEnabled) {
        $tierProperty = $policy.autoRevertScopes.PSObject.Properties | Where-Object { $_.Name -eq $riskTier }
        if ($tierProperty) {
            $autoRevertForTier = $tierProperty.Value
        }
    }

    if ($autoRevertForTier) {
        # Auto-revert this item
        if ($PSCmdlet.ShouldProcess("$($item.SiteUrl)/$($item.ItemPath)", "Revert $($item.DriftType) drift")) {
            Write-Host "  Auto-reverting [$riskTier]: $($item.SiteUrl) — $($item.ItemPath)"
            $revertRecord = Invoke-PermissionRevert -DriftItem $item -Policy $policy
            $reversionLog += $revertRecord
        }
    }
    else {
        # Queue for approval
        Write-Host "  Queuing for approval [$riskTier]: $($item.SiteUrl) — $($item.ItemPath)"

        $approvalRecord = [pscustomobject]@{
            approvalId        = [guid]::NewGuid().ToString()
            siteUrl           = $item.SiteUrl
            itemPath          = $item.ItemPath
            driftType         = $item.DriftType
            riskTier          = $riskTier
            riskScore         = $item.RiskScore
            before            = $item.Before
            after             = $item.After
            requestedAt       = (Get-Date).ToString('o')
            approvalDeadline  = (Get-Date).AddHours($policy.approvalGate.approvalWindowHours).ToString('o')
            status            = 'pending'
            assignedApprovers = $policy.approvalGate.approvers
            onTimeout         = $policy.approvalGate.onTimeout
        }

        $pendingApprovals += $approvalRecord

        # Send approval request email
        Send-ApprovalRequest -DriftItem $item -ApprovalGate $policy.approvalGate
    }
}

# Save reversion log
$reportDir = Split-Path $DriftReportPath -Parent
if ($reversionLog.Count -gt 0) {
    $reversionLogPath = Join-Path $reportDir "reversion-log-$(Get-Date -Format 'yyyyMMddTHHmmss').json"
    $reversionLog | ConvertTo-Json -Depth 10 | Set-Content -Path $reversionLogPath -Encoding UTF8
    Write-Host "Reversion log saved: $reversionLogPath"
}

# Save pending approvals
if ($pendingApprovals.Count -gt 0) {
    $pendingApprovalsPath = Join-Path $reportDir 'pending-approvals.json'
    $pendingApprovals | ConvertTo-Json -Depth 10 | Set-Content -Path $pendingApprovalsPath -Encoding UTF8
    Write-Host "Pending approvals saved: $pendingApprovalsPath"
}

#endregion

# Return summary
[pscustomobject]@{
    Status        = 'ReversionComplete'
    RevertedCount = $reversionLog.Count
    PendingCount  = $pendingApprovals.Count
    ReversionMode = $policy.reversionMode
    AutoRevertOverride = $AutoRevert.IsPresent
}
