#!/usr/bin/env python3
"""Build site-docs/ from source docs and solution READMEs, then validate nav."""

import json
import re
import shutil
from pathlib import Path

try:
    import yaml
except ImportError:
    yaml = None  # type: ignore[assignment]

from traceability import FRAMEWORK_BLOB_ROOT

ROOT = Path(__file__).resolve().parent.parent
SOURCE_DOCS = ROOT / "docs"
SITE_DOCS = ROOT / "site-docs"
SOLUTIONS_ROOT = ROOT / "solutions"
CONFIG_PATH = ROOT / "scripts" / "solution-config.yml"
MKDOCS_PATH = ROOT / "mkdocs.yml"
SOLUTION_CATALOG_PATH = ROOT / "data" / "solution-catalog.json"
TIER_MATRIX_PATH = SOURCE_DOCS / "reference" / "tier-applicability.md"

TIER_ORDER = ("baseline", "recommended", "regulated")


def load_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def load_yaml(path: Path):
    text = path.read_text(encoding="utf-8")
    if yaml is not None:
        # Use a loader that tolerates the !!python/name tags MkDocs uses for superfences
        loader = yaml.SafeLoader
        loader.add_multi_constructor(
            "tag:yaml.org,2002:python/",
            lambda loader, suffix, node: None,
        )
        return yaml.load(text, Loader=loader)  # noqa: S506
    # Fallback: try JSON in case the file is JSON-formatted YAML
    return json.loads(text)


def rewrite_solution_links(content: str) -> str:
    """Rewrite relative links in solution docs for the site-docs context.

    - docs/playbooks/... -> absolute framework site URL
    - ./docs/ prefix -> stripped (sibling page reference)
    - docs/ prefix -> stripped
    """

    def replace_link(match):
        prefix, path, suffix = match.group(1), match.group(2), match.group(3)
        if path.startswith(("http://", "https://", "#", "mailto:")):
            return match.group(0)
        # Framework playbook / control links
        if "playbooks/control-implementations" in path or path.startswith("docs/controls"):
            clean = path.lstrip("./")
            return f"{prefix}{FRAMEWORK_BLOB_ROOT}/{clean}{suffix}"
        # Solution-to-solution links should target site-docs index.md files.
        if re.fullmatch(r"(?:\.\./)+\d{2}-[a-z0-9-]+/?", path):
            return f"{prefix}{path.rstrip('/')}/index.md{suffix}"
        if re.fullmatch(r"(?:\.\./)+\d{2}-[a-z0-9-]+/README\.md", path):
            return f"{prefix}{path[:-9]}index.md{suffix}"
        # Root docs/ links from solution READMEs (../../docs/X.md -> ../../X.md in site-docs)
        if path.startswith("../../docs/"):
            clean = "../../" + path[len("../../docs/"):]
            return f"{prefix}{clean}{suffix}"
        # Strip docs/ prefix for intra-solution links
        clean = path
        if clean.startswith("./docs/"):
            clean = clean[7:]
        elif clean.startswith("docs/"):
            clean = clean[5:]
        return f"{prefix}{clean}{suffix}"

    return re.sub(r"(\[[^\]]*\]\()([^)]+)(\))", replace_link, content)


def copy_markdown_tree(source: Path, destination: Path) -> None:
    if destination.exists():
        shutil.rmtree(destination)
    shutil.copytree(source, destination)


def _tier_cell(solution: dict, tier: str) -> str:
    """Render a single tier cell for the tier-applicability matrix.

    - tier not in tiers_supported -> struck-through (no shipped config)
    - tier_maturity == placeholder -> ``*`` suffix (config is a scaffold only)
    - the tier matching tier_recommended is bolded (primary fit)
    """
    supported = tier in solution.get("tiers_supported", [])
    if not supported:
        return "~~\u2705~~"
    mark = "\u2705"
    if solution.get("tier_maturity") == "placeholder":
        mark = f"{mark}*"
    if tier == solution.get("tier_recommended"):
        mark = f"**{mark}**"
    return mark


def render_tier_matrix_rows(catalog: list) -> list:
    """Build the data rows for the tier-applicability matrix from the catalog."""
    rows = []
    for solution in catalog:
        rows.append(
            "| {id} | {name} | {priority} | {track} | {baseline} | "
            "{recommended} | {regulated} | {tier_recommended} |".format(
                id=solution["id"],
                name=solution["display_name"],
                priority=solution["priority"],
                track=solution["track"],
                baseline=_tier_cell(solution, "baseline"),
                recommended=_tier_cell(solution, "recommended"),
                regulated=_tier_cell(solution, "regulated"),
                tier_recommended=solution["tier_recommended"],
            )
        )
    return rows


def update_tier_applicability_matrix() -> None:
    """Regenerate the tier-applicability matrix table from the canonical catalog.

    The page documents that it is sourced from ``data/solution-catalog.json`` and
    regenerated by this script so it stays in lockstep with the catalog. This
    rewrites only the table data rows in place, preserving all surrounding prose.
    """
    if not TIER_MATRIX_PATH.exists() or not SOLUTION_CATALOG_PATH.exists():
        return

    catalog = sorted(load_json(SOLUTION_CATALOG_PATH), key=lambda s: s["id"])
    new_rows = render_tier_matrix_rows(catalog)

    lines = TIER_MATRIX_PATH.read_text(encoding="utf-8").splitlines()
    data_row = re.compile(r"^\|\s*\d{2}\s*\|")
    start = next((i for i, line in enumerate(lines) if data_row.match(line)), None)
    if start is None:
        raise SystemExit(
            f"Could not locate the matrix data rows in {TIER_MATRIX_PATH}."
        )
    end = start
    while end < len(lines) and data_row.match(lines[end]):
        end += 1

    rebuilt = lines[:start] + new_rows + lines[end:]
    output = "\n".join(rebuilt) + "\n"
    if output != TIER_MATRIX_PATH.read_text(encoding="utf-8"):
        TIER_MATRIX_PATH.write_text(output, encoding="utf-8")


def validate_nav(nav, base: Path) -> list:
    missing = []
    if isinstance(nav, str):
        target = base / nav
        if not target.exists():
            missing.append(str(target))
    elif isinstance(nav, list):
        for item in nav:
            missing.extend(validate_nav(item, base))
    elif isinstance(nav, dict):
        for value in nav.values():
            missing.extend(validate_nav(value, base))
    return missing


def main() -> None:
    config = load_json(CONFIG_PATH)
    mkdocs = load_yaml(MKDOCS_PATH)

    update_tier_applicability_matrix()

    SITE_DOCS.mkdir(parents=True, exist_ok=True)
    copy_markdown_tree(SOURCE_DOCS, SITE_DOCS)

    reference_dir = SITE_DOCS / "reference"
    reference_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(ROOT / "CHANGELOG.md", reference_dir / "changelog.md")

    for slug in config["solutions"].keys():
        solution_dir = SOLUTIONS_ROOT / slug
        output_dir = SITE_DOCS / "solutions" / slug
        output_dir.mkdir(parents=True, exist_ok=True)

        readme_path = solution_dir / "README.md"
        if readme_path.exists():
            readme_text = readme_path.read_text(encoding="utf-8")
            (output_dir / "index.md").write_text(
                rewrite_solution_links(readme_text), encoding="utf-8"
            )

        docs_dir = solution_dir / "docs"
        if docs_dir.exists():
            for doc_path in docs_dir.glob("*.md"):
                target = output_dir / doc_path.name
                target.write_text(
                    rewrite_solution_links(doc_path.read_text(encoding="utf-8")),
                    encoding="utf-8",
                )

    missing = validate_nav(mkdocs["nav"], SITE_DOCS)
    if missing:
        msg = "Missing MkDocs nav files:\n" + "\n".join(sorted(missing))
        raise SystemExit(msg)

    print("Documentation build inputs refreshed successfully.")


if __name__ == "__main__":
    main()
