<#
.SYNOPSIS
    Shared utility functions for the Microsoft Purview Communication Compliance Configurator solution.

.DESCRIPTION
    Provides ConvertTo-Hashtable, Merge-Hashtable, and Get-SolutionConfiguration
    functions used by Deploy-Solution.ps1, Monitor-Compliance.ps1, and
    Export-Evidence.ps1. Extracted to eliminate ~100 lines of duplication per script.
#>

function ConvertTo-Hashtable {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [AllowNull()]
        [object]$InputObject
    )

    if ($null -eq $InputObject) {
        return $null
    }

    if ($InputObject -is [System.Collections.IDictionary]) {
        $dictionary = @{}
        foreach ($key in $InputObject.Keys) {
            $dictionary[$key] = ConvertTo-Hashtable -InputObject $InputObject[$key]
        }

        return $dictionary
    }

    if ($InputObject -is [pscustomobject]) {
        $dictionary = @{}
        foreach ($property in $InputObject.PSObject.Properties) {
            $dictionary[$property.Name] = ConvertTo-Hashtable -InputObject $property.Value
        }

        return $dictionary
    }

    if (($InputObject -is [System.Collections.IEnumerable]) -and -not ($InputObject -is [string])) {
        $items = @()
        foreach ($item in $InputObject) {
            $items += ,(ConvertTo-Hashtable -InputObject $item)
        }

        return $items
    }

    return $InputObject
}

function Merge-Hashtable {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [hashtable]$Base,

        [Parameter(Mandatory)]
        [hashtable]$Overlay
    )

    $merged = @{}
    foreach ($key in $Base.Keys) {
        $merged[$key] = $Base[$key]
    }

    foreach ($key in $Overlay.Keys) {
        if ($merged.ContainsKey($key) -and ($merged[$key] -is [hashtable]) -and ($Overlay[$key] -is [hashtable])) {
            $merged[$key] = Merge-Hashtable -Base $merged[$key] -Overlay $Overlay[$key]
        }
        else {
            $merged[$key] = $Overlay[$key]
        }
    }

    return $merged
}

function Get-SolutionConfiguration {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$ConfigRoot,

        [Parameter(Mandatory)]
        [ValidateSet('baseline', 'recommended', 'regulated')]
        [string]$Tier
    )

    $defaultConfigPath = Join-Path $ConfigRoot 'default-config.json'
    $tierConfigPath = Join-Path $ConfigRoot ('{0}.json' -f $Tier)

    if (-not (Test-Path -Path $defaultConfigPath)) {
        throw 'Default configuration file not found.'
    }

    if (-not (Test-Path -Path $tierConfigPath)) {
        throw 'Configuration tier file not found.'
    }

    $defaultConfig = ConvertTo-Hashtable -InputObject ((Get-Content -Path $defaultConfigPath -Raw) | ConvertFrom-Json)
    $tierConfig = ConvertTo-Hashtable -InputObject ((Get-Content -Path $tierConfigPath -Raw) | ConvertFrom-Json)
    $mergedConfig = Merge-Hashtable -Base $defaultConfig -Overlay $tierConfig
    $mergedConfig['tier'] = $Tier

    return $mergedConfig
}

function Get-PolicyCatalogDefinitions {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [hashtable]$Config
    )

    return @{
        CopilotAIDisclosure = [ordered]@{
            templateId = 'CopilotAIDisclosure'
            policyName = 'CCC-Copilot-AI-Disclosure'
            policyType = 'AI disclosure review'
            scope = $Config['supervisedCommunicationTypes']
            keywords = @('generated by copilot', 'ai-assisted draft', 'drafted with copilot')
            conditions = @(
                'Customer-facing communication contains AI attribution or draft disclaimer.',
                'Reviewer validates that the disclosure is retained before release.'
            )
            controlMappings = @('3.4', '3.9')
            regulatoryMappings = @('FINRA 2210', 'SEC Reg BI')
            severity = 'Medium'
            notes = 'Supports compliance with AI disclosure and transparency expectations for Copilot-assisted communications.'
        }
        FinancialAdviceReview = [ordered]@{
            templateId = 'FinancialAdviceReview'
            policyName = 'CCC-Financial-Advice-Review'
            policyType = 'financial advice review'
            scope = $Config['supervisedCommunicationTypes']
            keywords = @('portfolio allocation', 'personalized recommendation', 'risk tolerance', 'suitable for you')
            conditions = @(
                'Communication references investor profile, recommendations, or suitability language.',
                'Reviewer validates that advice language aligns to approved supervisory standards.'
            )
            controlMappings = @('3.4', '3.5', '3.6')
            regulatoryMappings = @('FINRA 2210', 'FINRA 3110', 'SEC Reg BI')
            severity = 'High'
            notes = 'Supports compliance with supervisory review requirements for Copilot-assisted financial advice content.'
        }
        PromotionalLanguageReview = [ordered]@{
            templateId = 'PromotionalLanguageReview'
            policyName = 'CCC-Promotional-Language-Review'
            policyType = 'promotional content review'
            scope = $Config['supervisedCommunicationTypes']
            keywords = @('guaranteed returns', 'outperform the market', 'safe investment', 'risk free')
            conditions = @(
                'Communication includes promotional phrasing that may trigger FINRA 2210 review.',
                'Reviewer validates balanced presentation of risks and disclosures.'
            )
            controlMappings = @('3.4', '3.5')
            regulatoryMappings = @('FINRA 2210')
            severity = 'High'
            notes = 'Supports compliance with FINRA 2210 marketing and promotional content review expectations.'
        }
        BestInterestDisclosure = [ordered]@{
            templateId = 'BestInterestDisclosure'
            policyName = 'CCC-Best-Interest-Disclosure'
            policyType = 'best interest disclosure review'
            scope = $Config['supervisedCommunicationTypes']
            keywords = @('best interest', 'rollover recommendation', 'fee comparison', 'material limitation')
            conditions = @(
                'Communication references a recommendation that may require best-interest disclosure.',
                'Reviewer validates that required supporting disclosures are present.'
            )
            controlMappings = @('3.6', '3.9')
            regulatoryMappings = @('SEC Reg BI', 'FINRA 3110')
            severity = 'High'
            notes = 'Supports compliance with disclosure monitoring for recommendations and supervisory follow-up.'
        }
        ConflictOfInterestReview = [ordered]@{
            templateId = 'ConflictOfInterestReview'
            policyName = 'CCC-Conflict-Of-Interest-Review'
            policyType = 'conflict review'
            scope = $Config['supervisedCommunicationTypes']
            keywords = @('proprietary product', 'higher commission', 'revenue sharing', 'sales contest')
            conditions = @(
                'Communication indicates a possible conflict of interest or incentive alignment issue.',
                'Reviewer validates escalation to supervision or legal review when required.'
            )
            controlMappings = @('3.6', '3.9')
            regulatoryMappings = @('FCA SYSC 10', 'SEC Reg BI')
            severity = 'High'
            notes = 'Supports compliance with conflict-of-interest monitoring and oversight expectations.'
        }
        InsiderRiskCorrelation = [ordered]@{
            templateId = 'InsiderRiskCorrelation'
            policyName = 'CCC-Insider-Risk-Correlation'
            policyType = 'insider risk correlation'
            scope = $Config['supervisedCommunicationTypes']
            keywords = @('material non-public information', 'watch list account', 'deal room', 'private placement')
            conditions = @(
                'Communication includes insider risk indicators that may require cross-solution escalation.',
                'Reviewer coordinates with Microsoft Purview Insider Risk Management if an elevated pattern is detected.'
            )
            controlMappings = @('2.10', '3.6')
            regulatoryMappings = @('FINRA 3110', 'FCA SYSC 10')
            severity = 'High'
            notes = 'Supports compliance with insider risk detection planning when integrated with Microsoft Purview Insider Risk Management.'
        }
        RetailCommunicationEscalation = [ordered]@{
            templateId = 'RetailCommunicationEscalation'
            policyName = 'CCC-Retail-Communication-Escalation'
            policyType = 'supervisory escalation'
            scope = $Config['supervisedCommunicationTypes']
            keywords = @('principal approval', 'escalate to supervision', 'hold for review', 'legal approval required')
            conditions = @(
                'Communication has triggered review and now requires documented supervisory escalation.',
                'Reviewer validates linkage to the FINRA supervision workflow dependency.'
            )
            controlMappings = @('3.5', '3.6')
            regulatoryMappings = @('FINRA 2210', 'FINRA 3110')
            severity = 'High'
            notes = 'Supports compliance with reviewer escalation and documented supervision procedures.'
        }
        DualReviewSupervision = [ordered]@{
            templateId = 'DualReviewSupervision'
            policyName = 'CCC-Dual-Review-Supervision'
            policyType = 'dual review supervision'
            scope = $Config['supervisedCommunicationTypes']
            keywords = @('legal review', 'secondary reviewer', 'supervisor sign-off', 'retain for exam')
            conditions = @(
                'High-risk communication requires dual review before release or retention closeout.',
                'Reviewer validates secondary approval and evidence retention.'
            )
            controlMappings = @('3.6')
            regulatoryMappings = @('FINRA 3110', 'SEC Reg BI')
            severity = 'High'
            notes = 'Supports compliance with heightened supervision and examination support workflows.'
        }
    }
}

Export-ModuleMember -Function ConvertTo-Hashtable, Merge-Hashtable, Get-SolutionConfiguration, Get-PolicyCatalogDefinitions
